build:
	mpic++ -o tema2 tema2.cpp peer.cpp tracker.cpp -pthread -Wall

# run:
# 	mpirun -np 6 ./tema2

clean:
	rm -rf tema2

zip:
	zip -FSr 331CA_Sampetru_Mario_Tema2.zip *.cpp *.h Makefile README.md
